# Generated by Django 3.2.12 on 2023-02-28 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
