# Generated by Django 3.2.12 on 2023-03-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_seats_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
