# Generated by Django 3.2.12 on 2023-02-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='venue',
        ),
    ]
