# Generated by Django 3.2.12 on 2023-03-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20230308_0704'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
