# Generated by Django 3.2.12 on 2023-03-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_delete_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
